name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for the isssue. The owner has ben notified. '' first issue'
        pr-message: 'Thanks for the contributions. The owner has been notified and he will review thr pull request soon.Until then cheers.....'' first pr'
